info:
  contact:
    email: caiosousafernandesferreira@hotmail.com
    name: Caio Sousa
    url: http://www.swagger.io/support
  license:
    name: BrisaNet 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
swagger: "2.0"
