name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3

    - name: Build
      run: go build -v ./...

    - name: Test Projects
      run: go test -v ./webservice/projetos
    - name: Test Teams
      run: go test -v ./webservice/equipes
    - name: Test People
      run: go test -v ./webservice/pessoas
    - name: Test Tasks
      run: go test -v ./webservice/tasks